// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/combat.proto

package combat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerAction_ActionType int32

const (
	PlayerAction_START  PlayerAction_ActionType = 0
	PlayerAction_LEAVE  PlayerAction_ActionType = 1
	PlayerAction_ATTACK PlayerAction_ActionType = 2
)

// Enum value maps for PlayerAction_ActionType.
var (
	PlayerAction_ActionType_name = map[int32]string{
		0: "START",
		1: "LEAVE",
		2: "ATTACK",
	}
	PlayerAction_ActionType_value = map[string]int32{
		"START":  0,
		"LEAVE":  1,
		"ATTACK": 2,
	}
)

func (x PlayerAction_ActionType) Enum() *PlayerAction_ActionType {
	p := new(PlayerAction_ActionType)
	*p = x
	return p
}

func (x PlayerAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_combat_proto_enumTypes[0].Descriptor()
}

func (PlayerAction_ActionType) Type() protoreflect.EnumType {
	return &file_protos_combat_proto_enumTypes[0]
}

func (x PlayerAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAction_ActionType.Descriptor instead.
func (PlayerAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_protos_combat_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string                  `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action   PlayerAction_ActionType `protobuf:"varint,2,opt,name=action,proto3,enum=PlayerAction_ActionType" json:"action,omitempty"`
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_combat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_protos_combat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_protos_combat_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerAction) GetAction() PlayerAction_ActionType {
	if x != nil {
		return x.Action
	}
	return PlayerAction_START
}

type CombatState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitanId  string   `protobuf:"bytes,1,opt,name=titan_id,json=titanId,proto3" json:"titan_id,omitempty"`
	TitanHp  int32    `protobuf:"varint,2,opt,name=titan_hp,json=titanHp,proto3" json:"titan_hp,omitempty"`
	PlayerId []string `protobuf:"bytes,3,rep,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *CombatState) Reset() {
	*x = CombatState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_combat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatState) ProtoMessage() {}

func (x *CombatState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_combat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatState.ProtoReflect.Descriptor instead.
func (*CombatState) Descriptor() ([]byte, []int) {
	return file_protos_combat_proto_rawDescGZIP(), []int{1}
}

func (x *CombatState) GetTitanId() string {
	if x != nil {
		return x.TitanId
	}
	return ""
}

func (x *CombatState) GetTitanHp() int32 {
	if x != nil {
		return x.TitanHp
	}
	return 0
}

func (x *CombatState) GetPlayerId() []string {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

var File_protos_combat_proto protoreflect.FileDescriptor

var file_protos_combat_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x54, 0x54,
	0x41, 0x43, 0x4b, 0x10, 0x02, 0x22, 0x60, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x74, 0x61, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x74, 0x61, 0x6e, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x69, 0x74, 0x61, 0x6e, 0x5f, 0x68, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x74, 0x69, 0x74, 0x61, 0x6e, 0x48, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x32, 0x34, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x62, 0x61,
	0x74, 0x12, 0x2a, 0x0a, 0x05, 0x46, 0x69, 0x67, 0x68, 0x74, 0x12, 0x0d, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x62,
	0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a,
	0x17, 0x74, 0x68, 0x61, 0x6c, 0x6b, 0x7a, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x74, 0x61,
	0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_combat_proto_rawDescOnce sync.Once
	file_protos_combat_proto_rawDescData = file_protos_combat_proto_rawDesc
)

func file_protos_combat_proto_rawDescGZIP() []byte {
	file_protos_combat_proto_rawDescOnce.Do(func() {
		file_protos_combat_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_combat_proto_rawDescData)
	})
	return file_protos_combat_proto_rawDescData
}

var file_protos_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_combat_proto_goTypes = []interface{}{
	(PlayerAction_ActionType)(0), // 0: PlayerAction.ActionType
	(*PlayerAction)(nil),         // 1: PlayerAction
	(*CombatState)(nil),          // 2: CombatState
}
var file_protos_combat_proto_depIdxs = []int32{
	0, // 0: PlayerAction.action:type_name -> PlayerAction.ActionType
	1, // 1: Combat.Fight:input_type -> PlayerAction
	2, // 2: Combat.Fight:output_type -> CombatState
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_combat_proto_init() }
func file_protos_combat_proto_init() {
	if File_protos_combat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_combat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_combat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombatState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_combat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_combat_proto_goTypes,
		DependencyIndexes: file_protos_combat_proto_depIdxs,
		EnumInfos:         file_protos_combat_proto_enumTypes,
		MessageInfos:      file_protos_combat_proto_msgTypes,
	}.Build()
	File_protos_combat_proto = out.File
	file_protos_combat_proto_rawDesc = nil
	file_protos_combat_proto_goTypes = nil
	file_protos_combat_proto_depIdxs = nil
}
