// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: protos/greeter.proto

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	ServerMonologue(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ServerMonologueClient, error)
	ClientMonologue(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientMonologueClient, error)
	Conversation(ctx context.Context, opts ...grpc.CallOption) (Greeter_ConversationClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ServerMonologue(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ServerMonologueClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/Greeter/ServerMonologue", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServerMonologueClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_ServerMonologueClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterServerMonologueClient struct {
	grpc.ClientStream
}

func (x *greeterServerMonologueClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) ClientMonologue(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientMonologueClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/Greeter/ClientMonologue", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterClientMonologueClient{stream}
	return x, nil
}

type Greeter_ClientMonologueClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterClientMonologueClient struct {
	grpc.ClientStream
}

func (x *greeterClientMonologueClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterClientMonologueClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) Conversation(ctx context.Context, opts ...grpc.CallOption) (Greeter_ConversationClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/Greeter/Conversation", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterConversationClient{stream}
	return x, nil
}

type Greeter_ConversationClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterConversationClient struct {
	grpc.ClientStream
}

func (x *greeterConversationClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterConversationClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	ServerMonologue(*HelloRequest, Greeter_ServerMonologueServer) error
	ClientMonologue(Greeter_ClientMonologueServer) error
	Conversation(Greeter_ConversationServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) ServerMonologue(*HelloRequest, Greeter_ServerMonologueServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerMonologue not implemented")
}
func (UnimplementedGreeterServer) ClientMonologue(Greeter_ClientMonologueServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientMonologue not implemented")
}
func (UnimplementedGreeterServer) Conversation(Greeter_ConversationServer) error {
	return status.Errorf(codes.Unimplemented, "method Conversation not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ServerMonologue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).ServerMonologue(m, &greeterServerMonologueServer{stream})
}

type Greeter_ServerMonologueServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterServerMonologueServer struct {
	grpc.ServerStream
}

func (x *greeterServerMonologueServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_ClientMonologue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ClientMonologue(&greeterClientMonologueServer{stream})
}

type Greeter_ClientMonologueServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterClientMonologueServer struct {
	grpc.ServerStream
}

func (x *greeterClientMonologueServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterClientMonologueServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_Conversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).Conversation(&greeterConversationServer{stream})
}

type Greeter_ConversationServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterConversationServer struct {
	grpc.ServerStream
}

func (x *greeterConversationServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterConversationServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerMonologue",
			Handler:       _Greeter_ServerMonologue_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientMonologue",
			Handler:       _Greeter_ClientMonologue_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Conversation",
			Handler:       _Greeter_Conversation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/greeter.proto",
}
