name: client
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
